name: Terraform Apply with Vault

on:
  push:
    branches:
      - ec2

jobs:
  terraform-vpc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Set aws environment variables
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }}" >> $GITHUB_ENV  # AWS Access Key from GitHub Secrets
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV  # AWS Secret Key from GitHub Secrets


    - name: Terraform Init
      run: terraform init
      working-directory: ./ec2-instance-module  # Specify your Terraform directory

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./ec2-instance-module

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./ec2-instance-module



  